### ISSUE TITLE
-1 mean dynamic shape or Static shape?

### ISSUE THREAD

**Issue by 462630221** [onnx/optimizer#100]
-1 mean what? dynamic shape or Static shape? Using  the latest version（v0.3.1）,  -1 dim will be constant fold. In old version, It doesn't fold. So that cause some conflict.

**Comment by HSQ79815** [comment]
-1 means dynamic shape. In the latest version，we add some passes that can fold or fuse dynamic shape.

**Comment by daquexian** [comment]
Update: according to ONNX spec, "-1" is not a dynamic shape, and is not accepted by onnx backends like onnxruntime. If your model contains "-1" as a shape, please post an issue in the repo of the exporter you used.

Related issue of PaddlePaddle: https://github.com/PaddlePaddle/Paddle2ONNX/issues/928
