### ISSUE TITLE
optimizer support for python 3.11

### ISSUE THREAD

**Issue by ptoupas** [onnx/optimizer#107]
It seems like the optimizer currently does not support python 3.11.
I was wondering if you plan on supporting that since there are quite some performance improvements compared to prior python versions.

**Comment by daquexian** [comment]
thanks for your issue. I'll support it in the next week

**Comment by ptoupas** [comment]
Is there any update regarding this issue?

**Comment by daquexian** [comment]
> Is there any update regarding this issue?

sorry for the late response. I'm trying supporting python 3.11 in a branch. Hopefully it can be supported tomorrow.

**Comment by ptoupas** [comment]
> > Is there any update regarding this issue?
> 
> sorry for the late response. I'm trying supporting python 3.11 in a branch. Hopefully it can be supported tomorrow.

Amazing! Thanks a lot @daquexian

**Comment by daquexian** [comment]
@ptoupas Python 3.11 is supported in the latest release 0.3.6. Feel free to reopen this issue if you have any further problems.
