### ISSUE TITLE
optimization passes

### ISSUE THREAD

**Issue by ohjunee** [onnx/optimizer#141]
1. why did the onnx optimizer name the factor for optimization "pass"? Is there a reason ??

2. I want to do an impact measurement by layer/operator (fused layer/module) to see how it affects the layer optimized with onnx optimizer, is there any evidence that it improves performance?

**Comment by daquexian** [comment]
> why did the onnx optimizer name the factor for optimization "pass"? Is there a reason ??

It is from the compiler field. Initially a "pass" means traversing the computation graph once, now people use it to describe something like pattern matching.

**Comment by daquexian** [comment]
> I want to do an impact measurement by layer/operator (fused layer/module) to see how it affects the layer optimized with onnx optimizer, is there any evidence that it improves performance?

 you might want to use onnxsim, which is a more powerful tool based on onnx optimizer

**Comment by daquexian** [comment]
closing. feel free to reopen it if you have any further questions
