### ISSUE TITLE
How to prohibit constant reuse

### ISSUE THREAD

**Issue by huihui1** [onnx/optimizer#145]
I have a model in which there are many constants with the same data, but I don’t want constants to be reused.
Is there an option to control this feature，thanks!

**Comment by daquexian** [comment]
Close in favor to https://github.com/daquexian/onnx-simplifier/issues/310

**Comment by huihui1** [comment]
Thank you for your reply, the 'eliminate duplicate initializr option cannot meet my needs. Adding or not adding it, my multiple constant operators (with the same content) will still become one constant operator.
