### ISSUE TITLE
ONNX optimizer - fuse_consecutive_reduce_unsqueeze crashes 

### ISSUE THREAD

**Issue by JianhuiD** [onnx/optimizer#29]
# Bug Report  (copy from https://github.com/onnx/onnx/issues/3229)

### Is the issue related to model conversion?
No

### Describe the bug
ONNX optimizer - fuse_consecutive_reduce_unsqueeze crashes 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Windows
- ONNX version (*e.g. 1.7*):    1.8.0
- Python version: 3.6.8
- GCC/Compiler version (if compiling from source): N/A
- CMake version: N/A
- Protobuf version: 3.8.0
- Visual Studio version (if applicable): N/A

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
model_optimized = onnx.optimizer.optimize(model, ["fuse_consecutive_reduce_unsqueeze"])
...
```
- Attach the ONNX model to the issue (where applicable)
[reduce_unsqueeze.zip](https://github.com/onnx/optimizer/files/5840290/reduce_unsqueeze.zip)

### Expected behavior
Except 1. no crash and 2. fuse for consecutive reduce and unsqueeze op in the attached model

### Notes

Any additional information

**Comment by daquexian** [comment]
Thanks for your issue! I'll check it tomorrow

**Comment by daquexian** [comment]
I have checked the model and believe that this bug has already been fixed in `onnxoptimizer`. Please install it by `pip3 install onnxoptimizer` and `import onnxoptimizer` instead of `onnx.optimizer`

**Comment by daquexian** [comment]
BTW, I'm afraid the unsqueeze in your model cannot be fused into reducesum, as the `axes` of reducesum op is 1 while that of unsqueeze op is 0.
