### ISSUE TITLE
onnx optimizer 0.2.4 crashes

### ISSUE THREAD

**Issue by tzhang-666** [onnx/optimizer#36]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
ONNX optimizer crashes

### System information
- OS Platform and Distribution (Microsoft Windows 10 Enterprise): 
- ONNX version : 1.8.1 
- Python version: 3.8.8
- Protobuf version: 3.14.0
![image](https://user-images.githubusercontent.com/80027003/109923003-2981b780-7cf9-11eb-8a3e-c86b7c82328a.png)

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import numpy as np
import onnx
import onnxoptimizer
import onnxruntime

original_model = onnx.load("dump.onnx")
onnx.checker.check_model(original_model)

batch_sz = 1
max_sent_len = 50
keep_going = np.array([True], dtype=np.bool)
max_trip_count = np.array([2], dtype=np.int64)
query_data = np.zeros((batch_sz, max_sent_len), dtype=np.int64)
sequence_lens = np.ones([1], dtype=np.int32)

sess = onnxruntime.InferenceSession("dump.onnx")
result = sess.run(None, {'max_trip_count': max_trip_count, 'keep_going_in': keep_going, 'query': query_data, 'sequence_lens':  sequence_lens})

# Crashed here!!!
onnxoptimizer.optimize(original_model)
```
- Attach the ONNX model to the issue (where applicable)

https://github.com/tzhang-666/issues/blob/master/dump.zip

### Expected behavior
Optimizer should not crash and give clues if the input is illegal.

### Notes

N/A.

**Comment by daquexian** [comment]
Thanks for your issue!

I'll check it soon

**Comment by daquexian** [comment]
BTW, are you from microsoft? :)

**Comment by daquexian** [comment]
Closing because the model is not legal

**Comment by tzhang-666** [comment]
@daquexian Thanks for your comments. 
Also hope onnx optimizer omit an message saying that the model is illegal, rather than crash down.
