### ISSUE TITLE
Can't install optimizer and simplifier on jetson agx xavier

### ISSUE THREAD

**Issue by O2andsAnoxia** [onnx/optimizer#45]
**The error had  occured when i install the onnx-simplifier on my jetson agx xavier using the command pip install onnx-simplifier:**

`(mmcv) aurora@aurora-desktop:~$ pip install onnx-simplifier

Collecting onnx-simplifier

 Using cached onnx-simplifier-0.3.5.tar.gz (13 kB)

Collecting onnx

 Using cached onnx-1.9.0.tar.gz (9.8 MB)

 Installing build dependencies ... done

 Getting requirements to build wheel ... done

 Installing backend dependencies ... done

  Preparing wheel metadata ... done

ERROR: Could not find a version that satisfies the requirement onnxoptimizer>=0.2.5 (from onnx-simplifier) (from versions: none)

ERROR: No matching distribution found for onnxoptimizer>=0.2.5 (from onnx-simplifier)`

**I guess maybe i should build the onnxoptimizer>=0.2.5 from source code ,but the following error occurred:**

`(mmcv) aurora@aurora-desktop:~/onnxoptimizer$ pip install -e .

Obtaining file:///home/aurora/onnxoptimizer

Collecting onnx

 Using cached onnx-1.9.0.tar.gz (9.8 MB)

 Installing build dependencies ... done

 Getting requirements to build wheel ... done

 Installing backend dependencies ... done

  Preparing wheel metadata ... done

Collecting typing-extensions>=3.6.2.1

 Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)

Requirement already satisfied: numpy>=1.16.6 in /home/aurora/.local/lib/python3.6/site-packages (from onnx->onnxoptimizer==0.2.6) (1.19.2)

Requirement already satisfied: protobuf in /home/aurora/.local/lib/python3.6/site-packages (from onnx->onnxoptimizer==0.2.6) (3.14.0)

Requirement already satisfied: six in /home/aurora/.local/lib/python3.6/site-packages (from onnx->onnxoptimizer==0.2.6) (1.15.0)

Building wheels for collected packages: onnx

 Building wheel for onnx (PEP 517) ... error

 ERROR: Command errored out with exit status 1:

  command: /home/aurora/archiconda3/envs/mmcv/bin/python3.6 /home/aurora/archiconda3/envs/mmcv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpi5sfy_km

cwd: /tmp/pip-install-0dnb9thf/onnx

 Complete output (83 lines):

 10:03:54.151479 git.c:344        trace: built-in: git rev-parse HEAD

 fatal: 不是一个 git 仓库（或者任何父目录）：.git

 running bdist_wheel

 running build

 running build_py

 running create_version

 running cmake_build

 Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/aurora/archiconda3/envs/mmcv/include/python3.6m', '-DPYTHON_EXECUTABLE=/home/aurora/archiconda3/envs/mmcv/bin/python3.6', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-0dnb9thf/onnx']

 -- The C compiler identification is GNU 7.5.0

 -- The CXX compiler identification is GNU 7.5.0

 -- Check for working C compiler: /usr/bin/cc

 -- Check for working C compiler: /usr/bin/cc -- works

 -- Detecting C compiler ABI info

 -- Detecting C compiler ABI info - done

 -- Detecting C compile features

 -- Detecting C compile features - done

 -- Check for working CXX compiler: /usr/bin/c++

 -- Check for working CXX compiler: /usr/bin/c++ -- works

 -- Detecting CXX compiler ABI info

 -- Detecting CXX compiler ABI info - done

 -- Detecting CXX compile features

 -- Detecting CXX compile features - done

 -- Found PythonInterp: /home/aurora/archiconda3/envs/mmcv/bin/python3.6 (found version "3.6.11")

 -- Found PythonLibs: /home/aurora/archiconda3/envs/mmcv/lib/libpython3.6m.so (found version "3.6.11")

 Generated: /tmp/pip-install-0dnb9thf/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto

 CMake Error at CMakeLists.txt:292 (message):

  Protobuf compiler not found

 Call Stack (most recent call first):

  CMakeLists.txt:323 (relative_protobuf_generate_cpp)

 
 -- Configuring incomplete, errors occurred!

 See also "/tmp/pip-install-0dnb9thf/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".

 /tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead

  % (opt, underscore_opt))

 Traceback (most recent call last):

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>

   main()

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main

   json_out['return_val'] = hook(**hook_input['kwargs'])

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel

   metadata_directory)

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 222, in build_wheel

   wheel_directory, config_settings)

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir

   self.run_setup()

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 259, in run_setup

   self).run_setup(setup_script=setup_script)

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 150, in run_setup

   exec(compile(code, __file__, 'exec'), locals())

  File "setup.py", line 359, in <module>

   'backend-test-tools = onnx.backend.test.cmd_tools:main',

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup

   return distutils.core.setup(**attrs)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/core.py", line 148, in setup

   dist.run_commands()

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/dist.py", line 955, in run_commands

   self.run_command(cmd)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/dist.py", line 974, in run_command

   cmd_obj.run()

  File "/tmp/pip-build-env-yprluil8/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run

   self.run_command('build')

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/cmd.py", line 313, in run_command

   self.distribution.run_command(command)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/dist.py", line 974, in run_command

   cmd_obj.run()

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/command/build.py", line 135, in run

   self.run_command(cmd_name)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/cmd.py", line 313, in run_command

   self.distribution.run_command(command)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/dist.py", line 974, in run_command

   cmd_obj.run()

  File "setup.py", line 233, in run

   self.run_command('cmake_build')

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/cmd.py", line 313, in run_command

   self.distribution.run_command(command)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/distutils/dist.py", line 974, in run_command

   cmd_obj.run()

  File "setup.py", line 219, in run

   subprocess.check_call(cmake_args)

  File "/home/aurora/archiconda3/envs/mmcv/lib/python3.6/subprocess.py", line 311, in check_call

   raise CalledProcessError(retcode, cmd)

 subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/aurora/archiconda3/envs/mmcv/include/python3.6m', '-DPYTHON_EXECUTABLE=/home/aurora/archiconda3/envs/mmcv/bin/python3.6', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-0dnb9thf/onnx']' returned non-zero exit status 1.

 ----------------------------------------

 ERROR: Failed building wheel for onnx

Failed to build onnx

ERROR: Could not build wheels for onnx which use PEP 517 and cannot be installed directly`

**Are the optimizer and simplifier supported  on the jetson platform?What shold i do,if they are supported.**

**Comment by daquexian** [comment]
> ERROR: Failed building wheel for onnx

It seems that onnx package doesn't support jetson. I suggest to optimize & simplify your onnx model on x86, and run the produced model on jetson

**Comment by O2andsAnoxia** [comment]
Thanks，i will try to do

**Comment by O2andsAnoxia** [comment]
onnx can be installed on jetson by conda install onnx

**Comment by storm12t48** [comment]
`Downloading onnx-simplifier-0.4.17.tar.gz (19.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 17.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/07/f2/924ec403c7030b0fd202b8755d3d368a2adce683779f05351b48698cb151/onnx-simplifier-0.4.17.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/07/f2/924ec403c7030b0fd202b8755d3d368a2adce683779f05351b48698cb151/onnx-simplifier-0.4.17.tar.gz (from super-gradients) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
`

**Comment by prakhar199** [comment]
> Discarding https://files.pythonhosted.org/packages/1e/a8/de6f65f50ac5c457f0a0fe1de8802f681b0c20650e0db23560a675319f71/onnx-simplifier-0.4.13.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.6): Requested onnxsim from https://files.pythonhosted.org/packages/1e/a8/de6f65f50ac5c457f0a0fe1de8802f681b0c20650e0db23560a675319f71/onnx-simplifier-0.4.13.tar.gz (from super-gradients) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim' Downloading onnx-simplifier-0.4.10.tar.gz (18.1 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 13.4 MB/s eta 0:00:00 Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> `
> 
> Two years later still the same problem I can't install onnx-simplifier and not onnx c to do calibration to have models in 8-bit precision Does anyone have a solution? Cordially

Any solution on this?

**Comment by RaffaeleGrandi-Inx** [comment]
Unfortunately same error:

`Discarding https://files.pythonhosted.org/packages/e5/cf/530c3645de1461841ad677b500726fe26b554d9f7e987f83099042fc41c8/onnx-simplifier-0.4.33.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/e5/cf/530c3645de1461841ad677b500726fe26b554d9f7e987f83099042fc41c8/onnx-simplifier-0.4.33.tar.gz (from super-gradients) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'`

Moreover, after that, the system enter in a loop executing the package downgrade to the previous version, trying to install it again without evident positive results.

Any solution?

Thanks in advance for any help
Best regards

**Comment by havok69** [comment]
@RaffaeleGrandi-Inx  I have the exact same error and yes, my system enters a loop, trying to install the previous version of onnx-simplifier. I'm trying to install the package on a jetson xavier nx
