### ISSUE TITLE
Missing v0.2.6 git tag

### ISSUE THREAD

**Issue by yan12125** [onnx/optimizer#48]
Hi, I'm the maintainer of the unofficial Arch Linux package [python-onnxoptimizer](https://aur.archlinux.org/packages/python-onnxoptimizer/). That package uses git tags of this repository for building from sources. Recently, I noticed that [onnxoptimizer on PyPI](https://pypi.org/project/onnxoptimizer/) is updated to 0.2.6, while the v0.2.6 tag is [missing](https://github.com/onnx/optimizer/tags) from this repo. Could you add it? Thanks!

**Comment by daquexian** [comment]
Sorry for the late reply. Added :)

**Comment by yan12125** [comment]
No problem, thanks!
