### ISSUE TITLE
Unable to install on Mac M1

### ISSUE THREAD

**Issue by hossein1387** [onnx/optimizer#59]
Since this package is not available through pip,  I tried to build onnxoptimizer and unfortunately it fails with this error [error.log](https://github.com/onnx/optimizer/files/7559791/error.log)

Is there any plan to add support for Apple M1?

**Comment by ryanstout** [comment]
+1, thanks!

**Comment by AndrewZhaoLuo** [comment]
+1!

**Comment by grf53** [comment]
+1, Not only the M1, but also the general ARM devices. I got similar errors from a machine with ARM device.

**Comment by gttiankai** [comment]
+1

**Comment by grf53** [comment]
@daquexian How is it going? Due to this, I cannot update ONNX version to the later one after onnx-optimizer split.

**Comment by daquexian** [comment]
It is solved by #64. I will upload 0.2.7 package which supports m1 after ci finishes

**Comment by grf53** [comment]
Appreciated!!

**Comment by daquexian** [comment]
@grf53 Could you please try 'pip3 install onnxoptimizer' again? Thanks!

**Comment by grf53** [comment]
@daquexian I was late. It looks working. Thanks!

**Comment by daquexian** [comment]
> @daquexian I was late. It looks working. Thanks!

Great!

**Comment by berendkleinhaneveld** [comment]
Do you have any plans of publishing wheels to PyPI for arm platforms?
