### ISSUE TITLE
skip custom ops

### ISSUE THREAD

**Issue by minrui-hust** [onnx/optimizer#61]
Can I skip custom ops in optimization?
My onnx model is export by pytorch, and I do not have custom_lib, so the simplification always fails.
Is there a solution?

**Comment by daquexian** [comment]
And if you use onnxsim, you can try the beta version in https://convertmodel.com/#input=onnx&output=onnx, which doesn't need custom_lib

**Comment by daquexian** [comment]
If you have any further questions, please feel free to reopen this issue
