### ISSUE TITLE
execute "python3 -m onnxoptimizer model.onnx output.onnx" error

### ISSUE THREAD

**Issue by try1995** [onnx/optimizer#67]
Hi,
# python3 -m onnxoptimizer company_model.onnx company_model_opt.onnx
/usr/bin/python3: No module named onnxoptimizer.__main__; 'onnxoptimizer' is a package and cannot be directly executed

thx

**Comment by HSQ79815** [comment]
yeah, now onnxoptimizer don't support this feature,  we will supoort it sooner

**Comment by fengzf-github** [comment]
Using this project, how can I convert model files at present?

**Comment by HSQ79815** [comment]
@fengzf-github You can use onnx-optimizer in python script . 
1. Install onnxoptimizer.
```
git clone --recursive https://github.com/onnx/optimizer onnxoptimizer
cd onnxoptimizer
pip3 install -e .
```
2. convert your model in python script
```
import onnx
import onnxoptimizer

model = onnx.load("path to your model")
passes = onnxoptimizer.get_fuse_and_elimination_passes()
new_model = onnxoptimizer.optimize(model=model,passes=passes)
onnx.save(new_model, "path to save model")
```
