### ISSUE TITLE
How to add empty input to a node

### ISSUE THREAD

**Issue by wjj19950828** [onnx/optimizer#87]
hi~Now I am adding a fuse pass

Now I have encountered a problem, how to add an empty input to a node, ```Node->addInput``` seems to be unable to add an empty input

Call the following api in python
```python
node_def = helper.make_node(
    'Attention', # node name
    ['p2o.Add.6', 'qkv_weights', 'qkv_bias', '', '', 'extra_add_qk'],
    # ['p2o.Add.6', 'qkv_weights', 'qkv_bias', 'mask_index'],
    ['Y'], # outputs
    name='Attention',
    domain="com.microsoft",
    # attributes
    num_heads=9,
    unidirectional=0,
    )
```
You can create an Attention node with empty fourth and fifth inputs：
<img width="476" alt="image" src="https://user-images.githubusercontent.com/19977378/178194396-b83c7801-b5c8-4cad-b48d-0e6c8131555d.png">

How to create it in C++，thanks a lot~

**Comment by wjj19950828** [comment]
@daquexian Do you have any good suggestions～

**Comment by HSQ79815** [comment]
@wjj19950828 you can try it following
```C++
Tensor empty_tensor;
empty_tensor.sizes().push_back(0); // make the tensor dims to [0]
empty_tensor.elem_type() =  ONNX_NAMESPACE::TensorProto_DataType_FLOAT ;  // you should modify it  as needed
Value *empty_value = graph.addInitializerAndCreateValue(empty_tensor);  // create a value object

node->addInput(empty_value)  // add input to node in order

```

**Comment by wjj19950828** [comment]
@HSQ79815 thank you for your reply～

my code as follow
```code
Tensor mask_index, past;
 
mask_index.sizes().push_back(0); // Add mask_index empty node
mask_index.elem_type() = TensorProto_DataType_INT32;
past.sizes().push_back(0); // Add mask_index empty node
past.elem_type() = TensorProto_DataType_FLOAT;
Value *attention_inputs_mask_index = graph.addInitializerAndCreateValue(mask_index);
Value *attention_inputs_past = graph.addInitializerAndCreateValue(past);

attention_node->addInput(attention_inputs_mask_index);
attention_node->addInput(attention_inputs_past);
```
The generated Attention Node is as shown below
![image](https://user-images.githubusercontent.com/19977378/178227083-8dea8441-0ff4-403b-b870-6ee5393e35bb.png)

But when I run forward with ORT, the following error will be reported
![image](https://user-images.githubusercontent.com/19977378/178227215-05500a5c-8b90-4552-af7f-581ba79ade4d.png)

The specific reason is because the [code here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/contrib_ops/cpu/bert/attention.cc#L83) causes

It means that ```past``` tensor does not consider it to be ```nullptr``` in ORT

But in the following Attention Node ORT can run
![image](https://user-images.githubusercontent.com/19977378/178227516-579c8bcf-1a05-4fa9-aa72-2b2a0eeb852a.png)

Do you know how I should modify,thanks a lot~

**Comment by HSQ79815** [comment]
@wjj19950828 are you able to share your model ? I  try to reproduce

**Comment by wjj19950828** [comment]
@HSQ79815 The reproduction script and the onnx model are at the following link

```Attention.onnx``` is the onnx model of a single Attention node generated by a python script, which can be run by ```onnx_run.py```

```ner_model_test_0706.onnx```is the onnx model I generated by adding the attention fuse pass, the empty node is generated by the above code, but running ORT will report the above error

链接: https://pan.baidu.com/s/1bN-1VgJ9I8CxpHfDQxrQhg?pwd=mwhh 提取码: mwhh

感谢～

**Comment by HSQ79815** [comment]
@wjj19950828 Great, I will debug it sooner

**Comment by HSQ79815** [comment]
@wjj19950828  
```c++
auto* empty_node = g->create(kUndefined, 1);
empty_node->output()->setUniqueName(""); // empty_node->output() is a `Value` that represents a empty tensor 

empty_node->insertBefore(node); // insert empty_node to node lists that should be topo sort

node->addInput(empty_node->output())
```
Are you able to use the above codes to verifying again ?

**Comment by wjj19950828** [comment]
@HSQ79815 thanks a lot~

The above code solved my problem
