### ISSUE TITLE
simplify can't find graph

### ISSUE THREAD

**Issue by ARozental** [onnx/optimizer#94]
example:
`
torch.onnx.export(torch_model, (batch1,{}), my_location, opset_version=13, input_names=my_input_names,
                      output_names = ['output'],dynamic_axes=dynamic_axes)
model_loaded = onnx.load(my_location)
model_loaded, check = simplify(model) # raises error 'MyModel' object has no attribute 'graph'

`

**Comment by daquexian** [comment]
I believe you should use `simplify(model_loaded)` instead of `simplify(model)`.

Please feel free to reopen this issue if you have any further questions.
