### ISSUE TITLE
Is a lower version of cmake be compatible with onnxoptimizer?

### ISSUE THREAD

**Issue by gglin001** [onnx/optimizer#96]
the current CMakeLists.txt needs cmake > 3.22, it is too high for some "old" cmake projects to use it directly.
I wonder if it is possible to be compatible with a lower version of cmake?

**Comment by daquexian** [comment]
I'm afraid it is not easy. Do you encounter any problem?

**Comment by gglin001** [comment]
yes, I have a project needs cmake <=3.22(it is a pre-build project , hard to update cmake version), it just meets the minimum requirement of  onnxoptimizer, I can only use cmake==3.22.x now
