### ISSUE TITLE
No module named onnxoptimizer.__main__; 'onnxoptimizer' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by KOLANICH** [onnx/optimizer#99]

**Comment by HSQ79815** [comment]
yeah, onnxoptimizer is a package, you can import it and use api. Command-line API is in our [Roadmap](https://github.com/onnx/optimizer#roadmap)

**Comment by HSQ79815** [comment]
@KOLANICH  Now，Command-line API has been supported,  you can install from source code and run `onnxoptimizer <input.onnx> <output.onnx>`

**Comment by HSQ79815** [comment]
@KOLANICH Feel free to reopen this issue if you have any further problems.
